package com.largeblueberry.setting.serviceterm

data class TermSectionData(
    val titleKr: String,
    val titleEn: String,
    val contentKr: String,
    val contentEn: String
)

sealed class TermType(val id: String, val title: String, val sections: List<TermSectionData>) {
    object TermsOfService : TermType(
        id = "TOS",
        title = "서비스 이용약관",
        sections = listOf(
            TermSectionData(
                titleKr = "제1조 (목적 및 정의)",
                titleEn = "Article 1 (Purpose and Definition)",
                contentKr = "본 약관은 허밍을 악보(MIDI)로 변환해주는 '이어름' 서비스(이하 '서비스')의 이용 조건 및 절차에 관한 사항을 규정함을 목적으로 합니다.",
                contentEn = "The purpose of these Terms is to stipulate the conditions and procedures for the use of the 'E-eoreum' service (hereinafter referred to as the 'Service'), which converts humming into sheet music (MIDI)."
            ),
            TermSectionData(
                titleKr = "제2조 (회원가입 및 계정)",
                titleEn = "Article 2 (Membership and Account)",
                contentKr = "① 서비스는 구글 계정 연동을 통한 회원제로 운영되며, 안정적인 서비스 제공을 위해 무차별적인 업로드를 방지합니다. ② 회원은 하나의 계정으로 여러 기기에서 서비스를 이용할 수 있으나, 서비스의 정상적인 운영을 방해하는 행위는 금지됩니다.",
                contentEn = "① The Service operates on a membership basis through Google account linkage to prevent indiscriminate uploads and ensure stable service provision. ② Members may use the service on multiple devices with a single account, but actions that interfere with the normal operation of the service are prohibited."
            ),
            TermSectionData(
                titleKr = "제3조 (콘텐츠의 저작권)",
                titleEn = "Article 3 (Copyright of Content)",
                contentKr = "① 사용자가 허밍을 통해 생성한 MIDI 파일(악보)의 저작권은 사용자 본인에게 귀속됩니다. ② 서비스는 사용자의 동의 없이 생성된 악보를 상업적으로 이용하지 않습니다. 다만, 서비스 홍보 및 사례 소개 목적으로 악보를 익명화하여 사용할 수 있으며, 이 경우 사전에 사용자에게 별도 동의를 구합니다.",
                contentEn = "① The copyright of the MIDI file (sheet music) generated by the user's humming belongs to the user. ② The Service will not commercially use the generated sheet music without the user's consent. However, the Service may use anonymized sheet music for promotional or case study purposes, in which case separate consent will be obtained from the user in advance."
            ),
            TermSectionData(
                titleKr = "제4조 (사용자의 의무 및 금지 행위)",
                titleEn = "Article 4 (User Obligations and Prohibited Acts)",
                contentKr = "사용자는 다음 각 호의 행위를 하여서는 안 됩니다. 1. 자동화 봇 등을 이용한 대량 악보 생성 요청 등 서비스의 정상적인 운영을 방해하는 행위. 2. 타인의 저작권이 있는 음악을 무단으로 허밍하여 상업적으로 이용하는 행위. 3. 음란, 폭력적, 또는 기타 사회 통념에 어긋나는 내용을 허밍하는 행위.",
                contentEn = "Users must not engage in any of the following acts: 1. Acts that disrupt the normal operation of the Service, such as requesting mass sheet music generation using automated bots. 2. Unauthorized humming and commercial use of music copyrighted by others. 3. Humming content that is obscene, violent, or otherwise contrary to social norms."
            ),
            TermSectionData(
                titleKr = "제5조 (면책 조항)",
                titleEn = "Article 5 (Disclaimer)",
                contentKr = "① 서비스는 AI 기술을 기반으로 하므로, 생성된 악보의 정확성을 100% 보장하지 않으며, 이로 인해 발생하는 손해에 대해 책임을 지지 않습니다. ② 사용자가 생성한 악보로 인해 발생하는 저작권 침해 등 법적 문제에 대한 책임은 전적으로 사용자에게 있습니다.",
                contentEn = "① As the Service is based on AI technology, it does not guarantee 100% accuracy of the generated sheet music and is not liable for damages resulting therefrom. ② The user is solely responsible for any legal issues, such as copyright infringement, arising from the sheet music generated by the user."
            )
        )
    )

    object PrivacyPolicy : TermType(
        id = "PP",
        title = "개인정보 처리방침",
        sections = listOf(
            TermSectionData(
                titleKr = "제1조 (수집하는 개인정보 항목)",
                titleEn = "Article 1 (Personal Information Collected)",
                contentKr = "서비스는 회원가입 및 서비스 제공을 위해 다음 정보를 수집합니다. 1. 필수 항목: 구글 계정 정보(이메일 주소, 이름/닉네임), 음성 녹음 데이터(허밍). 2. 자동 생성 정보: 서비스 이용 기록, 접속 로그, 기기 정보(OS, 모델명) 등.",
                contentEn = "The Service collects the following information for membership and service provision: 1. Required Items: Google account information (email address, name/nickname), Voice Recording Data (Humming). 2. Automatically Generated Information: Service usage history, access logs, device information (OS, model name), etc."
            ),
            TermSectionData(
                titleKr = "제2조 (수집 및 이용 목적)",
                titleEn = "Article 2 (Purpose of Collection and Use)",
                contentKr = "수집된 개인정보는 다음 목적으로 이용됩니다. 1. 회원 관리: 회원 식별, 중복 가입 방지, 무분별한 활용 방지. 2. 서비스 제공: 음성 녹음 데이터를 악보 변환 AI 모델의 입력값으로 사용하여 악보를 생성 및 제공. 3. 서비스 개선: 이용 기록 분석을 통한 서비스 최적화 및 오류 분석.",
                contentEn = "The collected personal information is used for the following purposes: 1. Membership Management: Member identification, prevention of duplicate registration, customer inquiry response. 2. Service Provision: Using voice recording data as input for the sheet music conversion AI model to generate and provide sheet music. 3. Service Improvement: Service optimization and error analysis through usage history analysis."
            ),
            TermSectionData(
                titleKr = "제3조 (개인정보의 보유 및 파기)",
                titleEn = "Article 3 (Retention and Destruction of Personal Information)",
                contentKr = "① 원칙적으로 개인정보 수집 및 이용 목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. ② 음성 녹음 데이터 처리 정책: 악보 생성 요청 처리 후, 사용자의 음성 파일은 서버에서 즉시 파기됩니다.",
                contentEn = "① In principle, personal information is destroyed without delay after the purpose of collection and use is achieved. ② Voice Recording Data Processing Policy: After processing the sheet music generation request, the user's voice file is immediately destroyed from the server. (However, if [Optional Consent] is given, it may be stored for a certain period after anonymization for AI model performance improvement.)"
            ),
            TermSectionData(
                titleKr = "제4조 (개인정보 보호 책임자)",
                titleEn = "Article 4 (Chief Privacy Officer)",
                contentKr = """개인정보 보호 책임자는 다음과 같습니다. (졸업 작품 팀 정보)
소속: 졸업작품 팀 '이어름'
담당자: 신용우 (Android 개발자), 최찬호 (서버 개발자), 신윤재 (AI 개발자)
연락처: [onlym6659@gmail.com]""",
                contentEn = """The Chief Privacy Officer is as follows: (Graduation Project Team Information)
Affiliation: Graduation Project Team 'E-eoreum'
Contact Persons: Shin Yong-woo (Android Developer), Choi Chan-ho (Server Developer), Shin Yun-jae (AI Developer)
Contact: [onlym6659@gmail.com]"""
            )

        )
    )
}

fun findTermTypeById(id: String?): TermType? {
    return when (id) {
        TermType.TermsOfService.id -> TermType.TermsOfService
        TermType.PrivacyPolicy.id -> TermType.PrivacyPolicy
        else -> null
    }
}